trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    javaHomeOption: 'Path'
    mavenOptions: '-Xmx1024m'
    mavenVersionOption: 'Default'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(a5df71b4-0685-45c4-bca0-872ed1001ee1)'
    appType: 'webAppLinux'
    WebAppName: 'nexwork-contracts'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
    DeploymentTypeLinux: 'oneDeploy'
