app.start.mode: ${APP_START_MODE:dev}

spring:
  application:
    name: Contracts
  datasource:
    url: ${DB_HOST:}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8084

blockchain:
  service:
    host: ${BLOCKCHAIN_API_URI:http://localhost:8087/blockchain/v1/}
