spring.application.name: contracts
server.port: 8084


spring.datasource.url: jdbc:h2:mem:contractsdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

# Habilita consola web
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

blockchain.service.host: ${BLOCKCHAIN_API_URI:http://localhost:8087/blockchain/v1/}

logging:
  level:
    root: INFO
    ar.edu.unlam.tpi.accounts: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"