spring:
  application:
    name: contracts
  datasource:
    url: jdbc:h2:mem:contractsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
    path: /h2-console

server:
  port: 8084

blockchain:
  service:
    host: ${BLOCKCHAIN_API_URI:http://localhost:8087/blockchain/v1/}

logging:
  level:
    root: INFO
    ar.edu.unlam.tpi.contracts: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"