app.start.mode: ${APP_START_MODE:test}

spring:
  application:
    name: contracts
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS USERS\;CREATE SCHEMA IF NOT EXISTS CONTRACTS\;CREATE SCHEMA IF NOT EXISTS RECOM
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:data.sql

server:
  port: 8084

blockchain:
  service:
    host: ${BLOCKCHAIN_API_URI:http://localhost:8087/blockchain/v1/}