app.start.mode: ${APP_START_MODE:test}

spring:
  application:
    name: contracts
  datasource:
    url: jdbc:h2:mem:contractsdb;MODE=PostgreSQL;DEFAULT_SCHEMA=CONTRACTS
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: CONTRACTS
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  h2:
    console:
      enabled: true
    path: /h2-console

server:
  port: 8084

blockchain:
  service:
    host: ${BLOCKCHAIN_API_URI:http://localhost:8087/blockchain/v1/}